=== drozas/de/DE-PR05/grupo_investigacion.dtd
<!ELEMENT grupo_investigacion (profesor+, alumno*, asignatura+, linea_investigacion+,
								proyecto_investigacion+, pfc*, produccion) >
<!ELEMENT profesor (nombre, apellidos, email, pag_personal, tutoria*)>
	<!ATTLIST profesor  id ID #REQUIRED
						tipo (catedr치tico|titular|asociado|colaborador|ayudante) #REQUIRED
						despacho CDATA #IMPLIED
						asignaturas IDREFS #REQUIRED 
						tlfno CDATA #IMPLIED>
<!ELEMENT tutoria (#PCDATA)>
<!ELEMENT asignatura (nombre, palabra_clave*)>
	<!ATTLIST asignatura  id ID #REQUIRED
						car치cter (obligatoria|libre|opatativa|troncal) #REQUIRED
						forma (presencial|videoconferencia) #REQUIRED
						titulaci칩n CDATA #REQUIRED
						tipo (anual|cuatrimestral) #REQUIRED
						profesores IDREFS #REQUIRED 
						web CDATA #IMPLIED
						horario CDATA #IMPLIED
						aula CDATA #IMPLIED>		
<!ELEMENT palabra_clave (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT pag_personal (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT alumno (nombre, apellidos, email, pag_personal)>
	<!ATTLIST alumno  id ID #REQUIRED
						tipo (pfc|becario) #REQUIRED>	
<!ELEMENT linea_investigacion (nombre, palabra_clave*, descripcion) >
<!ELEMENT proyecto_investigacion (descripcion, entidad_financiadora, entidad*)>
	<!ATTLIST proyecto_investigacion  id ID #REQUIRED
						tipo CDATA #REQUIRED
						titulo CDATA #REQUIRED
						fecha_ini NMTOKEN #REQUIRED
						fecha_fin NMTOKEN #REQUIRED
						investigador_ppal IDREF #REQUIRED
						investigadores_ptes IDREFS #REQUIRED >
<!ELEMENT entidad_financiadora (#PCDATA)>
<!ELEMENT entidad (#PCDATA)>
<!ELEMENT pfc (descripcion, palabra_clave+)>
	<!ATTLIST pfc  id ID #REQUIRED
						titulacion CDATA #REQUIRED
						fecha_presearticulo_cientificontacion NMTOKEN #REQUIRED
						nota NMTOKEN #IMPLIED
						autores IDREFS #REQUIRED
						tutores IDREFS #REQUIRED >
<!ELEMENT produccion (articulo_cientifico*, seminario*)>
<!ELEMENT articulo_cientifico (nombre, palabra_clave*, resumen)>
	<!ATTLIST articulo_cientifico  id ID #REQUIRED
						a침o NMTOKEN #REQUIRED
						lineas_investigacion IDREFS #REQUIRED
						autores IDREFS #REQUIRED
						url CDATA #IMPLIED >
<!ELEMENT seminario (nombre, palabra_clave*, descripcion)>
	<!ATTLIST seminario  id ID #REQUIRED
						autores IDREFS #REQUIRED>

=== drozas/de/DE-PR05/grupo_investigacion_ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grupo_investigacion SYSTEM "grupo_investigacion.dtd" >
<grupo_investigacion>
  <profesor asignaturas="" despacho="" id="idvalue0" tipo="catedr치tico" tlfno="">
    <nombre>nombre</nombre>
    <apellidos>apellidos</apellidos>
    <email>email</email>
    <pag_personal>pag_personal</pag_personal>
    <tutoria>tutoria</tutoria>
  </profesor>
  <alumno id="idvalue1" tipo="pfc">
    <nombre>nombre</nombre>
    <apellidos>apellidos</apellidos>
    <email>email</email>
    <pag_personal>pag_personal</pag_personal>
  </alumno>
  <asignatura aula="" car치cter="obligatoria" forma="presencial" horario="" id="idvalue2" profesores="" tipo="anual" titulaci칩n="" web="">
    <nombre>nombre</nombre>
    <palabra_clave>palabra_clave</palabra_clave>
  </asignatura>
  <linea_investigacion>
    <nombre>nombre</nombre>
    <palabra_clave>palabra_clave</palabra_clave>
    <descripcion>descripcion</descripcion>
  </linea_investigacion>
  <proyecto_investigacion fecha_fin="nmtoken" fecha_ini="nmtoken" id="idvalue3" investigador_ppal="idvalue0" investigadores_ptes="" tipo="" titulo="">
    <descripcion>descripcion</descripcion>
    <entidad_financiadora>entidad_financiadora</entidad_financiadora>
    <entidad>entidad</entidad>
  </proyecto_investigacion>
  <pfc autores="" fecha_presentacion="nmtoken" id="idvalue4" nota="nmtoken" titulacion="" tutores="">
    <descripcion>descripcion</descripcion>
    <palabra_clave>palabra_clave</palabra_clave>
  </pfc>
  <produccion>
    <articulo_cientifico autores="" a침o="nmtoken" id="idvalue5" lineas_investigacion="" url="">
      <nombre>nombre</nombre>
      <palabra_clave>palabra_clave</palabra_clave>
      <resumen>resumen</resumen>
    </articulo_cientifico>
    <seminario autores="" id="idvalue6">
      <nombre>nombre</nombre>
      <palabra_clave>palabra_clave</palabra_clave>
      <descripcion>descripcion</descripcion>
    </seminario>
  </produccion>
</grupo_investigacion>
